### ISSUE TITLE
Glance volume not started when running setup

### ISSUE THREAD

**Issue by samos123** [tcpcloud/salt-formula-glusterfs#7]
Following error is seen when executing `salt 'ctl01*' state.sls glusterfs.server.setup`:

```
          ID: glusterfs_vol_glance_start
    Function: glusterfs.started
        Name: glance
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1628, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1494, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/glusterfs.py", line 209, in started
                  if isinstance(__salt__['glusterfs.status'](name), dict):
                File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 315, in status
                  root = _gluster_xml('volume status {0}'.format(name))
                File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 86, in _gluster_xml
                  raise CommandExecutionError(root.find('opErrstr').text)
              CommandExecutionError: Volume glance is not started
     Started: 23:54:50.663684
    Duration: 99.826 ms
     Changes:   
```

Workaround:
```
ssh ctl01
gluster volume start glance
gluster volume start keystone-keys
ssh cfg01
salt 'ctl01*' state.sls glusterfs.server.setup
```

**Comment by fpytloun** [comment]
This is a bug in some particular Salt version (which one are you using?)
As you can see, state `glusterfs.started` should ensure volume is started and it's failing because it's not started.
There used to be a conditional on salt version which was changing the behavior to workaround similar issue.

**Comment by AlexPostID** [comment]
I have faced the same issue. I'm using salt 2015.8.12

```
root@cfg01:/home/vagrant# apt-cache policy salt-minion
salt-minion:
  Installed: 2015.8.12+ds-1
  Candidate: 2015.8.12+ds-1
  Version table:
 *** 2015.8.12+ds-1 0
        500 http://apt.tcpcloud.eu/nightly/ trusty/extra amd64 Packages
        100 /var/lib/dpkg/status
     0.17.5+ds-1 0
        500 http://apt.tcpcloud.eu/nightly/ trusty/main amd64 Packages

root@cfg01:/home/vagrant# apt-cache policy salt-master
salt-master:
  Installed: 2015.8.12+ds-1
  Candidate: 2015.8.12+ds-1
  Version table:
 *** 2015.8.12+ds-1 0
        500 http://apt.tcpcloud.eu/nightly/ trusty/extra amd64 Packages
        100 /var/lib/dpkg/status
     0.17.5+ds-1 0
        500 http://apt.tcpcloud.eu/nightly/ trusty/main amd64 Packages
```

Maybe as workaround we can add `cmd.run` function with start command for volume, before `glusterfs.started` function to this file: https://github.com/tcpcloud/salt-formula-glusterfs/blob/master/glusterfs/server/setup.sls#L60 

Something like this:

```
glusterfs_vol_{{ name }}_start:
  cmd.run:
    - name: |
        gluster volume info keystone-keys | grep "Status: Started" ||  gluster volume start {{ name }}
  glusterfs.started:
    - name: {{ name }}
    - require:
      {%- if force_compatibility %}
      - cmd: glusterfs_vol_{{ name }}
      {%- else %}
      - glusterfs: glusterfs_vol_{{ name }}
      {%- endif %}
```

**Comment by fpytloun** [comment]
Yes, you need to use 2016.3.3 which should work and is available in xenial (I consider trusty to be obsolete as everything should be supported on xenial now).

There's one more workaround for this version here:
https://github.com/tcpcloud/salt-formula-glusterfs/blob/master/glusterfs/server/setup.sls#L3

So you can reuse `force_compatibility` variable for workaround with cmd.run. Will you make pull request?

**Comment by samos123** [comment]
You are right only the cfg01 node is currently using xenial:

```
salt --version
salt 2016.3.3 (Boron)
```

On other nodes:

```
apt-cache policy salt
N: Unable to locate package salt
root@ctl01:~# apt-cache policy salt-minion
salt-minion:
  Installed: 2015.8.12+ds-1
  Candidate: 2015.8.12+ds-1
  Version table:
 *** 2015.8.12+ds-1 0
        500 http://apt.tcpcloud.eu/nightly/ trusty/extra amd64 Packages
        100 /var/lib/dpkg/status
     0.17.5+ds-1 0
        500 http://apt.tcpcloud.eu/nightly/ trusty/main amd64 Packages
```

The current reclass models still uses trusty for ctl and computes @cznewt. I guess we need to update the models as well if it's considered obsolote. See below:

```
$ ack trusty
classes/system/linux/system/repo/tcp_salt.yml
6:          source: "deb [arch=amd64] http://apt.tcpcloud.eu/nightly/ trusty tcp-salt"

classes/system/reclass/storage/system/openstack_compute_single.yml
12:            linux_system_codename: trusty

classes/system/reclass/storage/system/openstack_proxy_single.yml
12:            linux_system_codename: trusty

classes/system/reclass/storage/system/openstack_control_cluster.yml
13:            linux_system_codename: trusty
27:            linux_system_codename: trusty
41:            linux_system_codename: trusty

classes/system/reclass/storage/system/openstack_compute_multi.yml
12:            linux_system_codename: trusty
21:            linux_system_codename: trusty

classes/system/reclass/storage/system/openstack_dashboard_single.yml
12:            linux_system_codename: trusty

classes/system/reclass/storage/system/mk22_lab_vagrant.yml
9:          - system.linux.system.trusty
24:          - system.linux.system.trusty
39:          - system.linux.system.trusty
54:          - system.linux.system.trusty
```

**Comment by samos123** [comment]
@fpytloun and @AlexPostID  just modified your code and verified that it works. I've submitted a pull request.
